# Generated by Django 6.0 on 2025-12-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('result', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
